services:
  consumer:
    build:
      context: ./consumer
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      DB_URL: "jdbc:postgresql://contract-db:5432/contract"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      PRODUCER_PORT: 8081
      PRODUCER_HOST: producer
      ACTIVEMQ_URL: "tcp://activemq:61616"
    depends_on:
      contract-db:
        condition: service_healthy
      zipkin:
        condition: service_started
      producer:
        condition: service_started
      activemq:
        condition: service_healthy

  producer:
    build:
      context: ./producer
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      DB_URL: "jdbc:postgresql://contract-db:5432/contract"
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      ZIPKIN_ENDPOINT: "http://zipkin:9411/api/v2/spans"
      ACTIVEMQ_URL: "tcp://activemq:61616"
    depends_on:
      contract-db:
        condition: service_healthy
      zipkin:
        condition: service_healthy
      activemq:
        condition: service_healthy

  contract-db:
    image: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "contract"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  activemq:
    image: symptoma/activemq:latest
    container_name: activemq
    ports:
      - "61616:61616" # ActiveMQ main port
      - "8161:8161"   # ActiveMQ web console
    environment:
      ACTIVEMQ_ADMIN_LOGIN: admin
      ACTIVEMQ_ADMIN_PASSWORD: admin
      ACTIVEMQ_NAME: localhost
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "61616"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - activemq_data:/data
      - activemq_logs:/var/log/activemq

volumes:
  db-data:
  activemq_data:
  activemq_logs: