package contracts

import org.springframework.cloud.contract.spec.Contract
import org.springframework.cloud.contract.spec.internal.HttpMethods

Contract.make {
    description 'Should save a post and return the saved post with a Content-Type header'

    request {
        urlPath '/posts'
        method 'POST'
        headers {
            contentType(applicationJson()) // Ensure request body is JSON
            accept(applicationJson())     // Server should accept JSON
        }
        body(
                id: null, // ID will be generated by the server
                title: $(consumer(regex('[a-zA-Z]+')), producer('Tool')), // Dynamic title
                content: $(consumer(regex('[a-zA-Z]+')), producer('Gradle')), // Dynamic content
                userId: $(consumer(anyNumber()), producer(1)) // Dynamic userId
        )
    }

    response {
        status 200 // Expect HTTP 200 OK
        headers {
            contentType(applicationJson()) // Ensure response contains Content-Type: application/json
        }
        body(
                id: 1, // Server generates ID
                title: 'Tool', // Server echoes back the title
                content: 'Gradle', // Server echoes back the content
                userId: 1 // Server echoes back the userId
        )
    }
}
