apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - image: baicham/spring-contract-consumer:bake1.0
        name: spring-contract-consumer
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        env:
        - name: DB_URL
          value: "jdbc:postgresql://contract-db:5432/contract"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: PRODUCER_PORT
          value: "8081"
        - name: PRODUCER_HOST
          value: "producer"
        - name: ZIPKIN_ENDPOINT
          value: "http://zipkin:9411/api/v2/spans"
        - name: ACTIVE_MQ_BROKER_URL
          value: tcp://activemq:61616
        - name: ACTIVEMQ_USER
          value: "admin"
        - name: ACTIVEMQ_PASSWORD
          value: "admin"
        - name: SWAGGER_CONFIG_URL
          value: "/consumer/v3/api-docs/swagger-config"
        - name: SWAGGER_API_DOCS_URL
          value: "/consumer/v3/api-docs"
        - name: SWAGGER_OAUTH2_REDIRECT_URL
          value: "/consumer/swagger-ui/oauth2-redirect.html"
        ports:
        - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
  - protocol: TCP
    port: 8085
    targetPort: 8085
    nodePort: 30085
