apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer
  labels:
    app: consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consumer
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: baicham/spring-contract-consumer:v3
          name: spring-contract-consumer
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: DB_URL
              value: "jdbc:postgresql://contract-db:5432/contract"
            - name: DB_USERNAME
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
            - name: PRODUCER_PORT
              value: "8081"
            - name: PRODUCER_HOST
              value: "producer"
            - name: ZIPKIN_ENDPOINT
              value: "http://zipkin:9411/api/v2/spans"
          ports:
            - containerPort: 8085

---
apiVersion: v1
kind: Service
metadata:
  name: consumer
spec:
  type: NodePort
  selector:
    app: consumer
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30085