apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer
  labels:
    app: producer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: producer
  template:
    metadata:
      labels:
        app: producer
    spec:
      containers:
      - image: baicham/spring-contract-producer:v4
        name: spring-contract-producer
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
        env:
        - name: DB_URL
          value: "jdbc:postgresql://contract-db:5432/contract"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres"
        - name: ZIPKIN_ENDPOINT
          value: "http://zipkin:9411/api/v2/spans"
        - name: ACTIVE_MQ_BROKER_URL
          value: tcp://activemq:61616
        - name: ACTIVEMQ_USER
          value: "admin"
        - name: ACTIVEMQ_PASSWORD
          value: "admin"
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  type: NodePort
  selector:
    app: producer
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30081
