name: CI

on:
  push:
    branches:
    - '*'
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Set up Maven
      uses: actions/setup-maven@v4
      with:
        maven-version: '3.9.1'

    - name: Setup Gradle
      uses: actions/setup-gradle@v4
      with:
        gradle-version: '8.1.1'

    - name: Build with Gradle
      run: |
        cd producer
        ./gradlew clean build

    - name: Publish to Maven Central
      run: |
        cd producer
        ./gradlew publish

    - name: Consumer test
      run: |
        cd consumer
        ./gradlew clean build
