name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Ensure Gradle Wrapper is Executable
      run: chmod +x gradlew

    - name: Verify Gradle Version
      run: ./gradlew --version

    - name: Build producer
      run: |
        ./gradlew :producer:clean :producer:build --stacktrace

    - name: Publish to stub jar Maven Central
      run: |
        ./gradlew :producer:publish

    - name: Test consumer
      run: |
        ./gradlew :consumer:clean :consumer:build -Dspring.profiles.active=test