name: CI

on:
  workflow_call:
    inputs:
      artifacts:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        artifact: ${{ fromJson(inputs.artifacts) || '[]'}}
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Ensure Gradle Wrapper is Executable
      run: chmod +x gradlew

    - name: Verify Gradle Version
      run: ./gradlew --version

    - name: Build producer
      run: |
        ./gradlew :producer:clean :producer:build --stacktrace
        
    - name: Upload stub artifact to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: producer-0.0.1-SNAPSHOT-stubs.jar
        path: producer/build/libs/producer-0.0.1-SNAPSHOT-stubs.jar

    - name: Download stub artifact from GitHub Packages
      uses: actions/download-artifact@v4
      with:
        name: ${{ matrix.artifact.name }}
        path: ${{ matrix.artifact.path }}

    - name: Build consumer
      run: |
        ./gradlew :consumer:clean :consumer:build