name: CI

on:
  workflow_call:
    inputs:
      artifacts:
        type: string
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Ensure Gradle Wrapper is Executable
      run: chmod +x gradlew

    - name: Verify Gradle Version
      run: ./gradlew --version

    - name: Build producer
      run: |
        ./gradlew :producer:clean :producer:build --stacktrace
        
    - name: Upload stub artifact to GitHub Packages
      uses: actions/upload-artifact@v4
      with:
        name: producer-0.0.1-SNAPSHOT-stubs-jar
        path: producer/build/libs/producer-0.0.1-SNAPSHOT-stubs.jar
        retention-days: 1

    - name: Print all artifacts for troubleshooting
      run: |
        echo "Artifacts list:"
        echo '${{ inputs.artifacts }}' | jq -c '.[]' | while read artifact; do
          name=$(echo "$artifact" | jq -r '.name')
          path=$(echo "$artifact" | jq -r '.path')
          echo "Artifact name: $name"
          echo "Artifact path: $path"
          echo ""
        done
        
    - name: Download artifacts dynamically
      run: |
        echo '${{ inputs.artifacts }}' | jq -c '.[]' | while read artifact; do
          name=$(echo "$artifact" | jq -r '.name')
          path=$(echo "$artifact" | jq -r '.path')
          echo "Creating step for downloading $name to $path"

          # Generate a YAML step to dynamically invoke actions/download-artifact
          echo "- name: Download $name" >> steps.yaml
          echo "  uses: actions/download-artifact@v4" >> steps.yaml
          echo "  with:" >> steps.yaml
          echo "    name: $name" >> steps.yaml
          echo "    path: $path" >> steps.yaml
        done

    - name: Rename stub jars
      run: |
        BASE_DIR=~/.m2/repository/com/abc/contracts/
        echo "Renaming JAR files under $BASE_DIR"
        find "$BASE_DIR" -type f -name '*-SNAPSHOT-stubs.jar' | while read jar; do
          RELEASE_JAR=$(echo "$jar" | sed 's/-SNAPSHOT-/-RELEASE-/')
          echo "Renaming $jar to $RELEASE_JAR"
          mv "$jar" "$RELEASE_JAR"
        done
        
    - name: Check the mvn repo
      run: |
        ls -ltra ~/.m2/repository/com/abc/contracts
        ls -ltra ~/.m2/repository/com/abc/contracts/producer
        ls -ltra ~/.m2/repository/com/abc/contracts/producer/0.0.1-RELEASE
      
    - name: Rename stub jars
      run: |
        BASE_DIR=~/.m2/repository/com/abc/contracts/
        echo "Renaming JAR files under $BASE_DIR"

        # Find and rename all JARs matching the pattern
        find "$BASE_DIR" -type f -name '*-SNAPSHOT-stubs.jar' | while read jar; do
          RELEASE_JAR=$(echo "$jar" | sed 's/-SNAPSHOT-/-RELEASE-/')
          echo "Renaming $jar to $RELEASE_JAR"
          mv "$jar" "$RELEASE_JAR"
        done
        
    - name: After rename Check the mvn repo
      run: |
        ls -ltra ~/.m2/repository/com/abc/contracts
        ls -ltra ~/.m2/repository/com/abc/contracts/producer
        ls -ltra ~/.m2/repository/com/abc/contracts/producer/0.0.1-RELEASE
    - name: Build consumer
      run: |
        ./gradlew :consumer:clean :consumer:build